server:
  port: 9411
  #port: 9000
  compression:
    enabled: true
spring:
  application:
    name: zipkin
    #zipkin:
    #base-url: http://localhost:9000/
management:
  metrics:
    web:
      server:
        #避免访问zipkin页面报java.lang.IllegalArgumentException
        auto-time-requests: false